// Copyright 2025 Oracynth, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// generatedDocFrontmatter is the VitePress front-matter block prepended to
// every page emitted by runDocsGen. It also doubles as the signature the
// stale-page pruner uses to decide whether a glx*.md file is one of ours
// (and therefore safe to delete) versus a hand-authored sibling.
const generatedDocFrontmatter = "---\neditLink: false\n---\n"

// runDocsGen writes per-command Markdown into outDir.
//
// Each file gets a VitePress front-matter block disabling the "Edit this page"
// link (the page is auto-generated; edits would be lost on the next make
// docs-cli). DisableAutoGenTag is set recursively because cobra/doc's default
// footer "Auto generated by spf13/cobra on <date>" rewrites daily and would
// make the CI drift check (docs-drift.yml) fail on every run that crosses
// midnight UTC.
//
// Stale-page handling: cobra/doc writes one file per available command but
// never deletes pages whose command was renamed or removed. We compute the
// expected filename set up front, run generation into outDir, and on success
// remove any glx*.md whose name is no longer in that set AND which carries
// our generated-doc front-matter signature. The signature check protects
// hand-authored siblings (e.g. a future docs/cli/glx_tips.md) and bounds the
// blast radius if a user runs `glx docs --output <wrong-path>`.
//
// On generation failure the prune step is skipped, leaving the previously-
// committed pages intact rather than producing a half-deleted, half-rewritten
// state.
func runDocsGen(cmd *cobra.Command, outDir string) error {
	if err := os.MkdirAll(outDir, dirPermissions); err != nil {
		return fmt.Errorf("create docs output dir %q: %w", outDir, err)
	}
	disableAutoGenTagRecursive(cmd)

	expected := expectedGeneratedFilenames(cmd)

	frontmatter := func(_ string) string {
		return generatedDocFrontmatter + "\n"
	}
	linkHandler := func(name string) string {
		return "/cli/" + strings.TrimSuffix(name, ".md")
	}
	if err := doc.GenMarkdownTreeCustom(cmd, outDir, frontmatter, linkHandler); err != nil {
		return fmt.Errorf("generate cobra markdown tree: %w", err)
	}

	return pruneStaleGenerated(outDir, expected)
}

func disableAutoGenTagRecursive(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, sub := range cmd.Commands() {
		disableAutoGenTagRecursive(sub)
	}
}

// expectedGeneratedFilenames mirrors cobra/doc's GenMarkdownTreeCustom
// traversal so the caller knows exactly which filenames a successful run
// produced (cobra/doc itself returns no such list).
func expectedGeneratedFilenames(cmd *cobra.Command) map[string]struct{} {
	names := make(map[string]struct{})
	var walk func(*cobra.Command)
	walk = func(c *cobra.Command) {
		names[strings.ReplaceAll(c.CommandPath(), " ", "_")+".md"] = struct{}{}
		for _, sub := range c.Commands() {
			if !sub.IsAvailableCommand() || sub.IsAdditionalHelpTopicCommand() {
				continue
			}
			walk(sub)
		}
	}
	walk(cmd)

	return names
}

// pruneStaleGenerated deletes glx*.md files in outDir that were NOT part of
// this run's expected output AND carry our generated-doc front-matter
// signature. The dual condition keeps hand-authored siblings safe even if
// they happen to match the glx*.md glob.
func pruneStaleGenerated(outDir string, expected map[string]struct{}) error {
	matches, err := filepath.Glob(filepath.Join(outDir, "glx*.md"))
	if err != nil {
		return fmt.Errorf("glob generated docs: %w", err)
	}
	for _, m := range matches {
		if _, ok := expected[filepath.Base(m)]; ok {
			continue
		}
		// m is a path produced by filepath.Glob from outDir + the literal
		// "glx*.md" pattern, so it cannot escape outDir; the gosec G304
		// check still flags variable file paths conservatively.
		body, err := os.ReadFile(m) // #nosec G304
		if err != nil {
			return fmt.Errorf("read %q: %w", m, err)
		}
		if !strings.HasPrefix(string(body), generatedDocFrontmatter) {
			continue
		}
		if err := os.Remove(m); err != nil {
			return fmt.Errorf("remove stale doc %q: %w", m, err)
		}
	}

	return nil
}
