// Copyright 2025 Oracynth, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

var docsOutput string

var docsCmd = &cobra.Command{
	Use:    "docs",
	Short:  "Regenerate CLI reference Markdown under docs/cli/",
	Hidden: true,
	RunE:   runDocs,
}

func init() {
	docsCmd.Flags().StringVarP(&docsOutput, "output", "o", "./docs/cli/", "output directory for generated docs")
}

func runDocs(_ *cobra.Command, _ []string) error {
	return runDocsGen(rootCmd, docsOutput)
}

// runDocsGen writes Markdown docs for cmd and all of its subcommands into outDir.
// Each file gets a VitePress front-matter block disabling the "Edit this page" link
// (the page is auto-generated; edits would be lost on the next make docs-cli).
//
// DisableAutoGenTag is set recursively because cobra/doc's default footer
// "Auto generated by spf13/cobra on <date>" rewrites daily and would make the
// CI drift check (docs-drift.yml) fail on every run that crosses midnight UTC.
func runDocsGen(cmd *cobra.Command, outDir string) error {
	if err := os.MkdirAll(outDir, dirPermissions); err != nil {
		return fmt.Errorf("create docs output dir %q: %w", outDir, err)
	}
	disableAutoGenTagRecursive(cmd)
	frontmatter := func(_ string) string {
		return "---\neditLink: false\n---\n\n"
	}
	linkHandler := func(name string) string {
		return "/cli/" + strings.TrimSuffix(name, ".md")
	}
	if err := doc.GenMarkdownTreeCustom(cmd, outDir, frontmatter, linkHandler); err != nil {
		return fmt.Errorf("generate cobra markdown tree: %w", err)
	}

	return nil
}

func disableAutoGenTagRecursive(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, sub := range cmd.Commands() {
		disableAutoGenTagRecursive(sub)
	}
}
