// Copyright 2025 Oracynth, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	glxlib "github.com/genealogix/glx/go-glx"
)

func TestMigrateStripStaleEventTitles_StripsAutoGeneratedShapes(t *testing.T) {
	archive := &glxlib.GLXFile{
		Persons: map[string]*glxlib.Person{
			"person-john": {Properties: map[string]any{"name": "John Smith"}},
			"person-robert": {Properties: map[string]any{
				"name": map[string]any{"value": "Robert Webb"},
			}},
			"person-jane": {Properties: map[string]any{"name": "Jane Miller"}},
		},
		Events: map[string]*glxlib.Event{
			"event-birth": {
				Title: "Birth of John Smith (1850)",
				Type:  glxlib.EventTypeBirth,
				Date:  "1850-03-15",
				Participants: []glxlib.Participant{
					{Person: "person-john", Role: glxlib.ParticipantRolePrincipal},
				},
			},
			// The buggy day-as-year suffix from #1025.
			"event-burial": {
				Title: "Burial of John Smith (15)",
				Type:  glxlib.EventTypeBurial,
				Participants: []glxlib.Participant{
					{Person: "person-john", Role: glxlib.ParticipantRolePrincipal},
				},
			},
			"event-marriage": {
				Title: "Marriage of Robert Webb and Jane Miller (1850)",
				Type:  glxlib.EventTypeMarriage,
				Participants: []glxlib.Participant{
					{Person: "person-robert", Role: glxlib.ParticipantRoleSpouse},
					{Person: "person-jane", Role: glxlib.ParticipantRoleSpouse},
				},
			},
			"event-bare": {
				Title: "Census (1863)",
				Type:  glxlib.EventTypeCensus,
			},
		},
	}

	report := migrateStripStaleEventTitles(archive)

	assert.Equal(t, 4, report.EventTitleYearsStripped)
	assert.Equal(t, "Birth of John Smith", archive.Events["event-birth"].Title)
	assert.Equal(t, "Burial of John Smith", archive.Events["event-burial"].Title)
	assert.Equal(t, "Marriage of Robert Webb and Jane Miller", archive.Events["event-marriage"].Title)
	assert.Equal(t, "Census", archive.Events["event-bare"].Title)
	// The year stays where it belongs — the event's date field.
	assert.Equal(t, glxlib.DateString("1850-03-15"), archive.Events["event-birth"].Date)
}

func TestMigrateStripStaleEventTitles_PreservesHandAuthoredTitles(t *testing.T) {
	archive := &glxlib.GLXFile{
		Persons: map[string]*glxlib.Person{
			"person-john": {Properties: map[string]any{"name": "John Smith"}},
		},
		Events: map[string]*glxlib.Event{
			// The literal example from the Event.Title doc comment.
			"event-census": {
				Title: "1860 Census — Webb Household",
				Type:  glxlib.EventTypeCensus,
				Participants: []glxlib.Participant{
					{Person: "person-john", Role: glxlib.ParticipantRolePrincipal},
				},
			},
			// Trailing year, but the prefix is not a derivable auto-title.
			"event-reunion": {
				Title: "Family reunion (1955)",
				Type:  glxlib.EventTypeGeneric,
				Participants: []glxlib.Participant{
					{Person: "person-john", Role: glxlib.ParticipantRolePrincipal},
				},
			},
			// Non-digit parenthetical.
			"event-household": {
				Title: "Census (Webb Household)",
				Type:  glxlib.EventTypeCensus,
			},
			// Auto shape but the participant's name doesn't match.
			"event-renamed": {
				Title: "Birth of Johann Schmidt (1850)",
				Type:  glxlib.EventTypeBirth,
				Participants: []glxlib.Participant{
					{Person: "person-john", Role: glxlib.ParticipantRolePrincipal},
				},
			},
			"event-untitled": {
				Type: glxlib.EventTypeBirth,
			},
		},
	}

	report := migrateStripStaleEventTitles(archive)

	assert.Equal(t, 0, report.EventTitleYearsStripped)
	assert.Equal(t, "1860 Census — Webb Household", archive.Events["event-census"].Title)
	assert.Equal(t, "Family reunion (1955)", archive.Events["event-reunion"].Title)
	assert.Equal(t, "Census (Webb Household)", archive.Events["event-household"].Title)
	assert.Equal(t, "Birth of Johann Schmidt (1850)", archive.Events["event-renamed"].Title)
}

// TestMigrateStripStaleEventTitles_IgnoresASSOParticipants confirms the gate
// is derived only from principal/spouse names — witness and officiant
// participants (appended by ASSO import after the title was generated) must
// neither block a legitimate strip nor enable one under the wrong name.
func TestMigrateStripStaleEventTitles_IgnoresASSOParticipants(t *testing.T) {
	archive := &glxlib.GLXFile{
		Persons: map[string]*glxlib.Person{
			"person-john":    {Properties: map[string]any{"name": "John Smith"}},
			"person-witness": {Properties: map[string]any{"name": "Willa Witness"}},
		},
		Events: map[string]*glxlib.Event{
			// Witness present: the principal-derived title still strips.
			"event-with-witness": {
				Title: "Baptism of John Smith (1850)",
				Type:  glxlib.EventTypeBaptism,
				Participants: []glxlib.Participant{
					{Person: "person-john", Role: glxlib.ParticipantRolePrincipal},
					{Person: "person-witness", Role: glxlib.ParticipantRoleWitness},
				},
			},
			// A title matching only the witness's name is not an auto shape.
			"event-witness-titled": {
				Title: "Baptism of Willa Witness (1850)",
				Type:  glxlib.EventTypeBaptism,
				Participants: []glxlib.Participant{
					{Person: "person-john", Role: glxlib.ParticipantRolePrincipal},
					{Person: "person-witness", Role: glxlib.ParticipantRoleWitness},
				},
			},
		},
	}

	report := migrateStripStaleEventTitles(archive)

	assert.Equal(t, 1, report.EventTitleYearsStripped)
	assert.Equal(t, "Baptism of John Smith", archive.Events["event-with-witness"].Title)
	assert.Equal(t, "Baptism of Willa Witness (1850)", archive.Events["event-witness-titled"].Title)
}

func TestMigrateStripStaleEventTitles_NoOpOnAlreadyMigratedArchive(t *testing.T) {
	archive := &glxlib.GLXFile{
		Persons: map[string]*glxlib.Person{
			"person-john": {Properties: map[string]any{"name": "John Smith"}},
		},
		Events: map[string]*glxlib.Event{
			"event-birth": {
				Title: "Birth of John Smith",
				Type:  glxlib.EventTypeBirth,
				Participants: []glxlib.Participant{
					{Person: "person-john", Role: glxlib.ParticipantRolePrincipal},
				},
			},
		},
	}

	report := migrateStripStaleEventTitles(archive)

	assert.Equal(t, 0, report.EventTitleYearsStripped)
	assert.Equal(t, "Birth of John Smith", archive.Events["event-birth"].Title)
}

// TestMigrateStripStaleEventTitles_IsIdempotent runs the migration twice and
// confirms the second run is a no-op: a cleaned title no longer carries a
// suffix to match.
func TestMigrateStripStaleEventTitles_IsIdempotent(t *testing.T) {
	archive := &glxlib.GLXFile{
		Persons: map[string]*glxlib.Person{
			"person-john": {Properties: map[string]any{"name": "John Smith"}},
		},
		Events: map[string]*glxlib.Event{
			"event-birth": {
				Title: "Birth of John Smith (1850)",
				Type:  glxlib.EventTypeBirth,
				Participants: []glxlib.Participant{
					{Person: "person-john", Role: glxlib.ParticipantRolePrincipal},
				},
			},
		},
	}

	first := migrateStripStaleEventTitles(archive)
	require.Equal(t, 1, first.EventTitleYearsStripped)

	second := migrateStripStaleEventTitles(archive)
	assert.Equal(t, 0, second.EventTitleYearsStripped)
	assert.Equal(t, "Birth of John Smith", archive.Events["event-birth"].Title)
}

// TestMigrateArchive_StripEventTitleYearSingleFileRoundTrip exercises the full
// archive load → migrate → write → reload pipeline on a single-file archive.
func TestMigrateArchive_StripEventTitleYearSingleFileRoundTrip(t *testing.T) {
	dir := t.TempDir()
	archivePath := filepath.Join(dir, "archive.glx")

	preMigration := `metadata:
  glx_version: "1.0"
persons:
  person-john:
    properties:
      name:
        value: "John Smith"
events:
  event-birth:
    title: "Birth of John Smith (1850)"
    type: birth
    date: "1850"
    participants:
      - person: person-john
        role: principal
  event-custom:
    title: "Family reunion (1955)"
    type: event
    participants:
      - person: person-john
        role: principal
`
	require.NoError(t, os.WriteFile(archivePath, []byte(preMigration), 0o600))

	t.Cleanup(func() { migrateStripEventTitleYear = false })
	migrateStripEventTitleYear = true
	require.NoError(t, migrateArchive(archivePath))

	written, err := os.ReadFile(archivePath)
	require.NoError(t, err)
	assert.NotContains(t, string(written), "Birth of John Smith (1850)")
	assert.Contains(t, string(written), "Birth of John Smith")
	assert.Contains(t, string(written), "Family reunion (1955)")

	reloaded, err := readSingleFileArchive(archivePath, false)
	require.NoError(t, err)
	require.Len(t, reloaded.Events, 2)
	assert.Equal(t, "Birth of John Smith", reloaded.Events["event-birth"].Title)
	assert.Equal(t, glxlib.DateString("1850"), reloaded.Events["event-birth"].Date)
	assert.Equal(t, "Family reunion (1955)", reloaded.Events["event-custom"].Title)

	// Idempotency at the fs boundary: a second invocation must be a no-op.
	require.NoError(t, migrateArchive(archivePath))
	second, err := os.ReadFile(archivePath)
	require.NoError(t, err)
	assert.Contains(t, string(second), "Birth of John Smith")
	assert.NotContains(t, string(second), "Birth of John Smith (1850)")
}
